### ISSUE TITLE
Handle completed task logic

### ISSUE THREAD

**Issue by daiHash** [ice-cream-the-fat-cat/fibonacci-app-frontend#31]
# TODO:
- [ ] Create page for completed rules
- [ ] Implement complete rules logic
   - [ ] Rule creation parameters:
   - [ ] Time
   - [ ] Yes/No value
   - [ ] User that is associated with the rule (id)
